services:
  - type: web
    name: smarthirex-backend
    env: python
    rootDir: .
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host=0.0.0.0 --port=$PORT
